# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d33cc7733079b94d38b21d31117d6b163317beb89f0441a07db761d10e509a20eac73037a01236cdd7a6c56559cd2efc7d8c2bcb8978c685ca3585f2a0b9fafa

test:
  secret_key_base: 85d43e701787a55d528e17abecacf374bce3b4f3e5c18b0cf98d25d424d97f53536602c03e96a90ce61da2b28048b5ca7f0ab43a682edbb93f47ca0f2a29fc96

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
